export const Category = {
  HOUSING: 'Housing',
  FOOD: 'Food & Dining',
  TRANSPORT: 'Transport',
  ENTERTAINMENT: 'Entertainment',
  SHOPPING: 'Shopping',
  HEALTH: 'Health',
  UTILITIES: 'Utilities',
  SAVINGS: 'Savings',
  SALARY: 'Salary',
  OTHER: 'Other',
};

export const CurrencyCodes = [
  'USD', 'EUR', 'GBP', 'JPY', 'AUD', 'CAD', 'CHF', 'CNY', 'HKD', 'NZD', 'SGD', 'INR', 'MMK',
  'BRL', 'RUB', 'KRW', 'MXN', 'SEK', 'NOK', 'DKK', 'ZAR', 'THB', 'IDR', 'PHP', 'VND', 'PKR', 'EGP', 'NGN', 'ARS', 'CLP', 'COP', 'PEN', 'TRY', 'ILS', 'SAR', 'AED', 'QAR', 'KZT', 'MYR', 'HUF', 'CZK', 'PLN', 'UAH', 'BGN', 'RON'
];

export const CURRENCIES = {
  USD: { code: 'USD', symbol: '$', name: 'US Dollar' },
  EUR: { code: 'EUR', symbol: '€', name: 'Euro' },
  GBP: { code: 'GBP', symbol: '£', name: 'British Pound' },
  JPY: { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  AUD: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  CAD: { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
  CHF: { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc' },
  CNY: { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  HKD: { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
  NZD: { code: 'NZD', symbol: 'NZ$', name: 'NZ Dollar' },
  SGD: { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  INR: { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  MMK: { code: 'MMK', symbol: 'Ks', name: 'Myanmar Kyat' },
  BRL: { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  RUB: { code: 'RUB', symbol: '₽', name: 'Russian Ruble' },
  KRW: { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
  MXN: { code: 'MXN', symbol: '$', name: 'Mexican Peso' },
  SEK: { code: 'SEK', symbol: 'kr', name: 'Swedish Krona' },
  NOK: { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
  DKK: { code: 'DKK', symbol: 'kr', name: 'Danish Krone' },
  ZAR: { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
  THB: { code: 'THB', symbol: '฿', name: 'Thai Baht' },
  IDR: { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
  PHP: { code: 'PHP', symbol: '₱', name: 'Philippine Peso' },
  VND: { code: 'VND', symbol: '₫', name: 'Vietnamese Dong' },
  PKR: { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee' },
  EGP: { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound' },
  NGN: { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  ARS: { code: 'ARS', symbol: '$', name: 'Argentine Peso' },
  CLP: { code: 'CLP', symbol: '$', name: 'Chilean Peso' },
  COP: { code: 'COP', symbol: '$', name: 'Colombian Peso' },
  PEN: { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol' },
  TRY: { code: 'TRY', symbol: '₺', name: 'Turkish Lira' },
  ILS: { code: 'ILS', symbol: '₪', name: 'Israeli Shekel' },
  SAR: { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal' },
  AED: { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  QAR: { code: 'QAR', symbol: '﷼', name: 'Qatari Riyal' },
  KZT: { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge' },
  MYR: { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  HUF: { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint' },
  CZK: { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna' },
  PLN: { code: 'PLN', symbol: 'zł', name: 'Polish Złoty' },
  UAH: { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia' },
  BGN: { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev' },
  RON: { code: 'RON', symbol: 'lei', name: 'Romanian Leu' },
};

